<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec.cr</string>
	</array>
	<key>name</key>
	<string>Crystal Spec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(before|after|around|background)\b(?![?!])</string>
			<key>name</key>
			<string>keyword.other.spec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#behaviour</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single-line-example</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pending</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#example</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#behaviour-with-multiline-desc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#example-with-multiline-desc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.crystal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>behaviour</key>
		<dict>
			<key>begin</key>
			<string>^\s*([fx]?(?:describe|context|feature))\b(?=.*\bdo\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.spec.behaviour</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Begin regexp must not match pending behaviours (see https://github.com/spec/spec-tmbundle/issues/31).</string>
			<key>end</key>
			<string>\b(do)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.crystal.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.spec.behaviour</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.crystal</string>
				</dict>
			</array>
		</dict>
		<key>behaviour-with-multiline-desc</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.spec.behaviour</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Behaviours with multiline descriptions are not matched by `behaviour`, so as a fallback we just highlight the bare keywords</string>
			<key>match</key>
			<string>^\s*([fx]?(?:describe|context|feature))\b</string>
			<key>name</key>
			<string>meta.spec.behaviour</string>
		</dict>
		<key>example</key>
		<dict>
			<key>begin</key>
			<string>^\s*([fx]?(?:it|specify|scenario))\b(?=.*\bdo\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.spec.example</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Begin regexp must not match pending behaviours (see https://github.com/spec/spec-tmbundle/issues/31).</string>
			<key>end</key>
			<string>\b(do)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.crystal.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.spec.example</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.crystal</string>
				</dict>
			</array>
		</dict>
		<key>example-with-multiline-desc</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.spec.example</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Examples with multiline descriptions are not matched by `behaviour`, so as a fallback we just highlight the bare keywords</string>
			<key>match</key>
			<string>^\s*([fx]?(?:it|specify|scenario))\b</string>
			<key>name</key>
			<string>meta.spec.example</string>
		</dict>
		<key>pending</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.spec.pending</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.crystal</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This only works with simple single / double quoted strings. But matching too liberally causes bugs (see https://github.com/spec/spec-tmbundle/issues/45), so better err on the safe side.</string>
			<key>match</key>
			<string>^\s*([fx]?(?:it|specify|scenario|describe|context|feature))\s+("[^"]*"|'[^']*')(?&lt;!do)\s*$</string>
			<key>name</key>
			<string>meta.spec.pending</string>
		</dict>
		<key>single-line-example</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.spec.example</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([fx]?(?:it|specify|scenario))\s*{</string>
		</dict>
	</dict>
	<key>scope</key>
	<string>source.crystal</string>
	<key>scopeName</key>
	<string>source.crystal.spec</string>
	<key>uuid</key>
	<string>0040F86C-5C8C-4187-9D0D-5072422FD1E0</string>
</dict>
</plist>
